path:
  models: ./models
  output: ./output
train:
  batch_size: 512
  validation_set_size: 0.2
  epochs: 20
data_set:
  epochs:
    train: [1, 2, 3, 4, 5, 6, 7, 8, 9]
    test: [10]
  image:
    height: 66
    width: 200
    channels: 3
    board_height: 150
  path: ./dataset