image:
    height: 66
    width: 200
    channel: 3
path:
    data_set: ./dataset
    models: ./models
    output: ./output
train:
    batch_size: 128
    validation_set_size: 0.1
epochs:
    train: [1, 2, 3, 4, 5, 6, 7, 8, 9]
    test: [10]